platform :ios, '11.0'

target 'WeatherDemoApp' do
  use_frameworks!
  pod 'WeatherFramework', :path => 'https://github.com/Amine-AKKARI/PSA.git', :branch => 'master'
end

target 'WeatherDemoAppTests' do
   inherit! :search_paths
   # Pods for testing
   pod 'WeatherFramework', :path => 'https://github.com/Amine-AKKARI/PSA.git', :branch => 'master'
 end

# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
